### ISSUE TITLE
Adaptive threshold in PSG

### ISSUE THREAD

**Issue by dailingjun** [RICE-EIC/E2Train#1]
In the line of 151-152 of 'model/predictive.py'
               if ctx.threshold < 0:
                    ctx.threshold = -1.0 * ctx.threshold * grad_msb_weight_abs.max()

What's the threshold when ctx.threshold >=0? Is it adaptive when ctx.threshold>=0?

**Comment by xhchrn** [comment]
Hi, thank you for your interest in our work.

When `ctx.threshold < 0`,  it is adaptive, because it is proportional to the max magnitude in the gradient of the current weight (`grad_msb_weight_abs`). In this case, `ctx.threshold` corresponds to beta at the end of the section 3 in the paper, which should be a small number from 0 to 1. In our paper, we found that 0.05 is usually a good choice.

When `ctx.threshold > 0`, then the threshold is faithfully set to whatever it is fed with. In this case, it is a fixed threshold.

**Comment by dailingjun** [comment]
Hmm, I see. Thank you very much.
